version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/acebook
hooks:
  # BeforeInstall:
  #   - location: bin/scripts/install-dependencies.sh
  #     timeout: 300
  #     runas: root
  AfterInstall:
    - location: bin/scripts/install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: bin/scripts/start-server.sh
      timeout: 150
      runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: root
